Merge dockerhub automated build version
kbase/Shock pull request #3
Opened 2017-06-16 23:15 UTC by sychan

This version should build a smaller standalone shock image automatically with docker hub. Also has docker-compose setup and initial make target that will bring up shock + mongo for testing within Travis. Actual tests are still to be written.

2017-06-16 23:32 UTC, kkellerlbl requested changes
The important change is removing my email.  Otherwise I think it looks ok.

2017-06-16 23:32 UTC, kkellerlbl commented on shock-server.cfg
> +email=kkeller@lbl.gov
Can we remove my email address from the example cfg file?

2017-06-16 23:32 UTC, kkellerlbl commented on shock-server.cfg
> +admin-email=sysadmins@kbase.us
These admin directives look like they're in the wrong place (even though they are actually in the existing CI shock.cfg file).

2017-06-16 23:32 UTC, kkellerlbl commented on shock-server.cfg
> +globus_token_url=https://ci.kbase.us/services/auth/api/legacy/globus/goauth/token?grant_type=client_credentials
Would Travis use these services, or would it spin up its own auth2 service for testing?

2017-06-17 03:30 UTC, sychan commented
@kkellerlbl All request changes made. Let me know if you think this is good to go so that I can test the automated build

2017-06-17 03:30 UTC, kkellerlbl approved these changes
Looks okay.

2017-06-17 03:30 UTC, merged